### ISSUE TITLE
Unexpected error when running Deephys on Silicon Mac, but app runs fine

### ISSUE THREAD

**Issue by jmayank23** [mjgroth/deephys-aio#1]
I am running Deephys on Silicon Mac, and it runs absolutely fine, but I keep getting "Unexpected Error" Message but the app still works. It's just that the error window comes up in the center of the screen and I cant move it back, forcing me to click on "Exit now." Sharing a screenshot as well for reference
<img width="1512" alt="Screen Shot 2023-06-21 at 9 53 26 PM" src="https://github.com/mjgroth/deephys-aio/assets/27727185/721c6e08-9c7a-4846-aedf-544e1c047468">

**Comment by mgroth0** [comment]
Thank you for the report. It should be fixed now. There is no need for you to update, as it was just a bug in the server.

Please let me know if it is fixed for you, whenever you get a chance.

**Comment by jmayank23** [comment]
Thank you for the prompt response! But I still see the same error message; for more context, I was using the "Category" option. 

<img width="1512" alt="Screen Shot 2023-06-22 at 8 40 12 AM" src="https://github.com/mjgroth/deephys-aio/assets/27727185/fbd6bf0d-c4df-440e-962f-edf933753639">

**Comment by jmayank23** [comment]
To me, it looks like the error pops up after a certain time, no matter which feature of the app I am using

**Comment by mgroth0** [comment]
Ah that's strange. Can you hit the "Submit Bug Report" whenever it happens? It sends me information that helps me solve it. Thank you!

**Comment by mgroth0** [comment]
I am no longer getting the error on my end, so I'm not quite sure why you are still getting it.

**Comment by mgroth0** [comment]
Nevermind, I got the error. It only happens sometimes. Looking into it...

**Comment by jmayank23** [comment]
Yeah, so for me, it crashes after 1min 4 seconds, and this happened twice (I was using a different feature of the app in these two runs.) Sharing one screen recording here for reference. 

https://github.com/mjgroth/deephys-aio/assets/27727185/a30fc229-e4b0-489e-a54b-4811e87756d8

**Comment by mgroth0** [comment]
Thanks for the video. I'll give you some context. It probably got nothing to do with what you do in the app. If you just open it and let it sit there, the error will probably pop up.

The app periodically talks to the server to see if a new version is available. For some reason, this server requst randomly throws a strange error sometimes, but not all the time.

**Comment by jmayank23** [comment]
Got it; thanks for letting me know!

If there was a way for you to allow the user to move the main window to the front (above the error window,) that'd be great!

**Comment by mgroth0** [comment]
Please try 1.35.9: https://github.com/mjgroth/deephys/releases/tag/1.35.9

If the problem persists, ignoring the error message could be an option. But I'd prefer not to do that and rather to ensure that there are no errors.

If you get an error again, if you could hit the "submit bug report" button or alternatively just copy and paste the full error text into here that would be very helpful. Thanks!

**Comment by jmayank23** [comment]
I think this one is working fine for me now! Thank you so much for the prompt responses and your help. 

I collaborated with Xavier in the past on a similar project and wanted to play around with this tool!

**Comment by mgroth0** [comment]
Thanks for checking it out. And thanks for helping me improve it!

**Comment by jmayank23** [comment]
Of course! I am happy to share my Github repo as well in case you think it will be helpful as an additional tutorial. The notebook contains code to fine-tune InceptionV4 on Caltech101 and then run Deephys

**Comment by mgroth0** [comment]
I'd be happy to add that to our tutorials! Would you be comfortable with me just linking your github repo directly?

**Comment by jmayank23** [comment]
Sure! I'm comfortable with whichever method you see fit to cite/credit the repo. [Here](https://github.com/jmayank23/Caltech101_Deephys_NeuralActivity) is the repository.
