### ISSUE TITLE
Viewing the False [Positive, Negative] samples

### ISSUE THREAD

**Issue by jmayank23** [mjgroth/deephys-aio#2]
Is it possible to see the specific False Negative sample?

<img width="1512" alt="Screen Shot 2023-06-22 at 8 45 18 AM" src="https://github.com/mjgroth/deephys-aio/assets/27727185/1fae4604-08cf-49e6-8e34-66f588bcff5e">

**Comment by mgroth0** [comment]
You should be able to. Have you tried scrolling down? Is the information underneath the pie chart what you are looking for?

**Comment by jmayank23** [comment]
Ah, yes, I didn't notice the scroll option. Thanks!
